### PR TITLE
Styling home page

### PR DESCRIPTION
**Pull request by Samah-Mustafa**

### CODE REVIEW

**Comment by Samah-Mustafa** [comment]
Hi @louisrli 
This PR is gathering all the unmerged previous files in the prvious pull requests, so every time I create a new PR the numbers of files doubled unless the previous ones merged
So as a result I suggest you not to review this PR till I merged the three other ones

**Comment by louisrli** [comment]
```
git checkout dev
git checkout -b mynewbranch
```
and start from the dev branch

unless your code depends on the code from previous branches

please look up "how to checkout files from master branch" and you can clean up this PR too

**Comment by louisrli** [comment]
or ask abdulrahman

**Comment by Samah-Mustafa** [comment]
@louisrli Many thanks for this note
I guess the mistake I was doing every time is creating a branch while being on another branch not being on the dev branch, that's why the branch was doubling the files 

Just ignore this branch because I have lots of issues with it, I created anew branch with the same content called (home-page-2nd-edition)

**Pull request closed without merging**
